// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTgmAZ_HcV7r_0fFrwxwAAZFY4xwzeWqc',
    appId: '1:497261661198:web:6bc88b1a3d9587e69c005f',
    messagingSenderId: '497261661198',
    projectId: 'authtutorial-aba35',
    authDomain: 'authtutorial-aba35.firebaseapp.com',
    storageBucket: 'authtutorial-aba35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwlLJH85f5VTjBAz2ucULxAq6SNjjW2E',
    appId: '1:497261661198:android:c109388a9f911fcf9c005f',
    messagingSenderId: '497261661198',
    projectId: 'authtutorial-aba35',
    storageBucket: 'authtutorial-aba35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxkiBeryuoFXi2prIqzlKpRilMe71t4vg',
    appId: '1:497261661198:ios:8f15e799ff4ca0829c005f',
    messagingSenderId: '497261661198',
    projectId: 'authtutorial-aba35',
    storageBucket: 'authtutorial-aba35.appspot.com',
    iosClientId: '497261661198-rmijeh4p1d15op5pj20gsob57sgcj93t.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxkiBeryuoFXi2prIqzlKpRilMe71t4vg',
    appId: '1:497261661198:ios:8f15e799ff4ca0829c005f',
    messagingSenderId: '497261661198',
    projectId: 'authtutorial-aba35',
    storageBucket: 'authtutorial-aba35.appspot.com',
    iosClientId: '497261661198-rmijeh4p1d15op5pj20gsob57sgcj93t.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
